[package]
name = "erdtree"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.1", features = ["derive"] }
crossbeam = "0.8.2"
hybrid-rc = "0.6.0"
ignore = "0.4.2"

[dev-dependencies]
tempdir = "0.3"
