[package]
name = "erdtree"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
clap = { version = "4.1.1", features = ["derive"] }
crossbeam = "0.8.2"
ignore = "0.4.2"
lscolors = { version = "0.13.0", features = ["ansi_term"] }
once_cell = "1.17.0"

[dev-dependencies]
tempdir = "0.3"
